### PR TITLE
1.1 Release Candidate

### PR DESCRIPTION
**Pull request by reece**
This PR is to collect final changes prior to the 1.1 release. Please comment below. PRs are also okay. 

**The deadline for responses is Friday September 4, 2020 at 5pm PDT.**

The most significant changes since 1.0:
* Many documentation content and formatting updates (normalization, dev process)
* Standardized on use of "VRS" as abbreviation for Variation Representation Specification
* Identifiable objects may be represented inline or by identifier. e.g., `Allele.location`
* Added new classes VariationSet, Haplotype, ChromosomalLocation, and CytobandInterval
* Rename abstract class Interval to SequenceInterval (no backward compatibility impact)

The above changes have been reviewed previously.

### CODE REVIEW

**Comment by larrybabb** [comment]
@reece This looks excellent overall. The only minor thing I saw (and it can be deferred) is that it looks like CytobandInterval is a sub-heading under SequenceInterval(Abstract) along with SimpleInterval.  This may be a bit misleading when looking at the way the headings are organized which mostly reflect the inheritance structure of the model.  I suppose we should have an Interval top-level heading with SequenceInterval and CytobandInterval underneath and then SimpleInterval under SequenceInterval. That said, I'm not sure it's worth changing for 1.1.

**Comment by helensch** [comment]
@reece looks good. For the schema diagrams I am not sure why Variation(Abstract) has a type of "Interval". The Location(Abstract) has a type of "Interval".

**Comment by ahwagner** [comment]
Looks great. Incorporated some very minor changes in 8f023fc and c072ec0. Nothing controversial. +1 to merge and release.

**Review by ahwagner — APPROVED** [review]

**Review by larrybabb — APPROVED** [review]
+1

**Pull request merged**
