### PR TITLE
revise docs to promote VRS alias

### PR DESCRIPTION
**Pull request by ahwagner**

### CODE REVIEW

**Comment by reece** [comment]
Works for me.
(This PR is marked as a draft, so can't be merged.)

**Comment by ahwagner** [comment]
Thanks @reece. I was hoping to change it in a few more places. Once finished I'll un-draft the PR for review and approval.

**Comment by ahwagner** [comment]
Leaving `1.0` alone and targeting `master` ahead of `1.1` release. Will fast-forward to `master` and go from there.

**Comment by reece** [comment]
Looks good to me. Thanks for doing this!

**Pull request merged**
